# _config.yml

# Site Settings
title: "Bread & Letters | Resource Hub"
description: "High-impact articles and expert insights to upskill your career and scale your business. Covering Excel, Power BI, Automation, Negotiation, Sales, and more."
url: "https://articles.breadandletters.com" 
baseurl: "" 
timezone: Asia/Kuala_Lumpur 

# Build Settings
markdown: kramdown
# Permalinks: Enforce categories in the URL structure
permalink: /:categories/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag 

# 🚨 CRITICAL FIX FOR GITHUB PAGES 🚨
# 1. Collections: Define the category pages as a custom collection
collections:
  pages:
    output: true
    permalink: /:path/
  
# 2. Force Jekyll to process folders starting with underscores (if applicable)
# If you kept your category pages in a folder like `_pages` or `categories`
include: ["_config.yml", "categories", "assets", "_posts"]

# Navigation/Category Menu
categories_menu:
  - title: "Productivity & Tech"
    url: "/productivity-tech/" 
    slug: "productivity-tech"
    description: "Excel, Power Platform, Automation, Coding"
  - title: "Professional Skills"
    url: "/professional-skills/" 
    slug: "professional-skills"
    description: "Negotiation, Presentation, Sales, Soft Skills"
  - title: "Business Strategy"
    url: "/business-strategy/" 
    slug: "business-strategy"
    description: "Scaling, Growth, Marketing, Finance"
  - title: "About Us"
    url: "/about/"
    slug: "about"
    description: "Learn about the team"

# External Links / Social (For traffic driving)
social:
  linkedin: "https://www.linkedin.com/company/breadandletters/" 
  twitter: "https://twitter.com/breadandletters" 

external_sites:
  academy_url: "https://academy.breadandletters.com" 
  consulting_url: "https://breadandletters.com" 

# Disqus Comments (Placeholder)
disqus:
  shortname: 

# Google Analytics
google_analytics: G-Z2NN7GLYTT